planning_plugin: "pilz_industrial_motion_planner/CommandPlanner"
request_adapters: ""
default_planner_config: "PTP"
capabilities: >
    pilz_industrial_motion_planner/MoveGroupSequenceAction
    pilz_industrial_motion_planner/MoveGroupSequenceService
planner_configs:
  PTP:
    group: arm
  LIN:
    group: arm
  CIRC:
    group: arm
