# 1. 컨트롤러 매니저 설정
controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# 2. 각 컨트롤러 세부 설정 (Velocity 제거됨)
arm_controller:
  ros__parameters:
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

gripper_traj_controller:
  ros__parameters:
    joints:
      - gripper_controller
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
